# Note:  This is an example config, see habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

BASE_TASK_CONFIG_PATH: "configs/tasks/pickplace_mp3d.yaml"
TRAINER_NAME: "rearrangement-behavior-cloning-distrib"
ENV_NAME: RearrangementRLEnv
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["disk"]
TENSORBOARD_DIR: "tb/object_rearrangement/v3/seed_1/"
VIDEO_DIR: "video_dir/object_rearrangement/v3/seed_1/"
# To evaluate on all episodes, set this to -1
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/pick_and_place/v3/seed_1/model_10.ckpt"
SHOW_TOP_DOWN_MAP: False
NUM_PROCESSES: 1
CHECKPOINT_FOLDER: "data/new_checkpoints/pick_and_place/v3/seed_1/"
OUTPUT_LOG_DIR: data/object_rearrangement/logs
LOG_INTERVAL: 10
LOG_METRICS: True
CHECKPOINT_INTERVAL: 1
DATASET_PATH: "data/datasets/object_rearrangement/v3/{split}/{scene_split}.db"
RESULTS_DIR: "data/object_rearrangement/results/{split}/{type}"
EVAL_RESUTLS_DIR: "data/object_rearrangement/results/"
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
EVAL:
  SPLIT: "val"

IL:
  POLICY:
    name: "PickPlacePolicy"

  USE_IW: True
  distrib_backend: GLOO
  BehaviorCloning:
    lr: 0.001
    max_epochs: 2
    batch_size: 1
    timestep_batch_size: 256
    freeze_encoder: False

MODEL:
  inflection_weight_coef: 6.975176928855059
  ablate_depth: False
  ablate_rgb: False
  ablate_instruction: False
  INSTRUCTION_ENCODER:
    vocab_size: 128
    embedding_size: 64
    hidden_size: 128
    use_pretrained_embeddings: False
    rnn_type: "LSTM"
    final_state_only: True
    bidirectional: False
  RGB_ENCODER:
    cnn_type: "ResnetRGBEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"
  STATE_ENCODER:
    hidden_size: 512
    rnn_type: "GRU"
    num_recurrent_layers: 2
  SEQ2SEQ:
    use_prev_action: True
  PROGRESS_MONITOR:
    use: False