NAVI:
  NUM_STEPS: 500
  FLAG_GT_OCC_MAP: True
  NUM_STEPS_EXPLORE: 10
  THRESH_REACH: 0.8
  HFOV: 360
  PERCEPTION: 'Potential' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'DP'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'Sqrt_R'

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_360degree_DP_GT_Potential_D_SqrtR_10STEP_500STEPS'
