NAVI:
  FLAG_VISUALIZE_MIDDLE_TRAJ: False

PRED:
  VIEW:
    MODEL_TYPE: 'knowledge_graph'
    BATCH_SIZE: 64
    DEVICE: cuda
    EPOCHS: 1000
    EVAL_INTERVAL: 1
    FLAG_VISUALIZE_PRED_LABELS: False
    LOSS_TYPE: L1
    NUM_WORKERS: 16
    RESUME: ''
    SAVED_FOLDER: 'output/model_weights_input_view'
    LR: 1e-3
    NUM_PROCESS: 1
    GEN_SAMPLES_SAVED_FOLDER: 'output/training_data_input_view_1000samples'
    PROCESSED_VIEW_SAVED_FOLDER: 'output/training_preprocessed_view_1000samples'
    EPS_SAVE_GAP: 20


SAVE:
  TESTING_RESULTS_FOLDER: ''

SEM_MAP:
  CELL_SIZE: 0.05
  GRID_CLASS_SIZE: 250
  FLAG_VISUALIZE_EGO_OBS: False

SENSOR:
  OBS_WIDTH: 512