NAVI:
  NUM_STEPS: 500
  FLAG_GT_OCC_MAP: True
  NUM_STEPS_EXPLORE: 10
  THRESH_REACH: 0.8
  HFOV: 360
  PERCEPTION: 'Potential' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'Greedy'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_360degree_Greedy_GT_Potential_10STEP_500STEPS'
