NAVI:
  FLAG_GT_OCC_MAP: true
  HFOV: 360
  PERCEPTION: Potential
  STRATEGY: Greedy

PRED:
  PARTIAL_MAP:
    BATCH_SIZE: 2
    CHECKNAME: unet
    DEVICE: cuda
    DIVIDE_AREA: 1000
    EPOCHS: 30
    EVAL_INTERVAL: 2
    FLAG_VISUALIZE_PRED_LABELS: false
    INPUT: occ_and_sem
    INPUT_CHANNEL: 45 # 42 + 3
    OUTPUT_CHANNEL: 4
    INPUT_WH: (128, 128)
    LOSS_TYPE: CE
    NEIGHBOR_SIZE: 20
    NUM_GENERATED_SAMPLES_PER_SCENE: 100
    NUM_WORKERS: 2
    RESUME: ''
    SAVED_FOLDER: 'output/model_weights_UNet_input_partial_map'
    STEP_GAP: 5
    LR: 1e-3
    NUM_PROCESS: 4

SAVE:
  TESTING_RESULTS_FOLDER: ''

SEM_MAP:
  CELL_SIZE: 0.1
  GRID_CLASS_SIZE: 42