NAVI:
  NUM_STEPS: 500
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  HFOV: 360
  PERCEPTION: Potential
  STRATEGY: FME
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  NUM_STEPS_EXPLORE: 1

PRED:
  VIEW:
    DIVIDE_AREA: 100
    INPUT: depth_and_sem
    NUM_GENERATED_SAMPLES_PER_SCENE: 100
    NUM_PROCESS: 24
    multiprocessing: 'single'
    GEN_SAMPLES_SAVED_FOLDER: 'output/training_data_input_view_1000samples'
    EPS_SAVE_GAP: 10
    FLAG_VIS_FRONTIER_ON_MAP: False


SAVE:
  TESTING_RESULTS_FOLDER: ''

SEM_MAP:
  CELL_SIZE: 0.05
  GRID_CLASS_SIZE: 250
  FLAG_VISUALIZE_EGO_OBS: False

SENSOR:
  OBS_WIDTH: 512