NAVI:
  NUM_STEPS: 500
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  NUM_STEPS_EXPLORE: 1
  THRESH_REACH: 0.8
  HFOV: 90
  PERCEPTION: 'Potential' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'Greedy'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'Sqrt_R'
  FLAG_VISUALIZE_FRONTIER_POTENTIAL: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SLURM:
  NUM_PROCESS: 20
  PROC_PER_GPU: 5